-- Prisma cannot represent functional indexes in schema.prisma. Product writes
-- still enforce case-insensitive uniqueness in the service; retain the normal
-- database unique constraint generated by @unique and remove schema drift.
DROP INDEX IF EXISTS "Product_publicName_normalized_key";
